<!DOCTYPE html>
<html>
<head>
  <title>App</title>
</head>
<body >
    <div style="background: rgba(122,186,245,1);
background: -moz-radial-gradient(center, ellipse cover, rgba(122,186,245,1) 0%, rgba(32,124,229,1) 100%);
background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%, rgba(122,186,245,1)), color-stop(100%, rgba(32,124,229,1)));
background: -webkit-radial-gradient(center, ellipse cover, rgba(122,186,245,1) 0%, rgba(32,124,229,1) 100%);
background: -o-radial-gradient(center, ellipse cover, rgba(122,186,245,1) 0%, rgba(32,124,229,1) 100%);
background: -ms-radial-gradient(center, ellipse cover, rgba(122,186,245,1) 0%, rgba(32,124,229,1) 100%);
background: radial-gradient(ellipse at center, rgba(122,186,245,1) 0%, rgba(32,124,229,1) 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#7abaf5', endColorstr='#207ce5', GradientType=1 );width: 100%;height: 100%">
      <a href="login.php">cpanel</a>
    </div>
</body>
</html>